config/routes.rb
Rails.application.routes.draw do
  get 'admins/login' => 'admins#login'
  get 'admins/logout' => 'sessions#destroy'
  get 'admins/list' => 'admins#list'
  post 'admins/update' => 'admins#admin_update'
  get 'admins/workload' => 'admins#admin_statistics_workload'
  get 'admins/jsonworkload' => 'admins#admin_workload_json'
  get 'admins/jsonlist' => 'admins#jsonlist'
  get 'admins/commodity/status_list' => 'commodity#status_list'
  get 'admins/commodity/json_status_list' => 'commodity#json_status_list'
  post 'admins/commodity/pass' => 'commodity#pass'
  post 'admins/commodity/update' => 'commodity#admin_update'
  get 'admins/businesses/status_list' => 'businesses#status_list'
  get 'admins/businesses/json_status_list' => 'businesses#json_status_list'
  post 'admins/businesses/pass' => 'businesses#pass'
  post 'admins/businesses/update' => 'businesses#admin_update'
  get 'admins/businesses/list' => 'businesses#list'
  get 'admins/businesses/json_list' => 'businesses#json_list'
  get 'admins/businesses/statistics' => 'businesses#statistics'
  get 'admins/businesses/json_statistics' => 'businesses#json_statistics'
  get 'admins/scenics/type' =>'scenics#scenics_option'
  get '/admins/commodity/list' => 'commodity#commodity_list'
  get '/admins/commodity/json_list' => 'commodity#commodity_json_list'
  get '/admins/orders/statistics' => 'orders#statistics'
  namespace :admins do

  end
  resources :admins
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
	def status_list
		@title="审核商家"
		respond_to do |format|
			format.js 
		end
	end

	def json_status_list
		@page = params[:page]
		@rows=params[:rows]
		@sort_column=params[:sidx]
		@sort=params[:sord]
		@businesses_hash=Business.new.get_json_status_list(current_admin.id, @page, @rows, @sort_column, @sort)
		render json: @businesses_hash
	end

	def pass
		@result=false
		case params[:oper]
		when "del"
			@result=Business.new.get_pass params[:id]
		end
		respond_to do |format|
			format.js { render 'shared/op_result' }
		end
	end

	def list
		@title="管理商家"
		respond_to do |format|
			format.js 
		end
	end

	def json_list
		page=params[:page]
		rows=params[:rows]
		sort_column=params[:sidx]
		sort=params[:sord]
		@businesses_hash=Business.new.get_json_list(current_admin.id, page, rows, sort_column, sort)
		render json: @businesses_hash
	end

	def admin_update
		@result=false
		case params[:oper]
		when 'edit'
			business=Business.find(params[:id])
			#update business
			name=params[:name]
			legal_person_name=params[:legal_person_name]
			legal_person_photo=params[:legal_person_photo]
			unless name.nil? 
				business.update_attribute(:name, name)
				business.update_attribute(:legal_person_name, legal_person_name)
				@result=true
			end
		when 'del'
			#delete business
			@result=Business.find(params[:id]).destroy
		end
		
		respond_to do |format|
			format.js  { render 'shared/op_result' }
		end
	end

  def statistics
    @businesses = Business.new.count_business
    @categories = ""
    1.upto(@businesses.length) do |n|
    	@categories += n.to_s
    	if n < @businesses.length
    		@categories += ","
    	end
    end
  end

  def json_statistics
    @businesses = Business.new.count_business
    # binding.pry
    render json: @businesses
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business_statistics.html.erb
<div class="breadcrumbs" id="breadcrumbs">

	<ul class="breadcrumb">
		<li>
			<i class="icon-home home-icon"></i>
				<a href="#">首页</a>
			</li>
		<li class="active">统计商家</li>
	</ul><!-- /.breadcrumb -->
</div>

<div class="page-content">
	<script src="assets/highcharts.js"></script>
	<!-- <script src="assets/exporting.js"></script> -->
	<!-- <div style="min-width: 310px; height: 400px; margin: 0 auto"> -->
		<span id="container1" style="float:left;min-width: 800px; height: 400px; margin: 0 auto"></span>
	<!-- </div> -->
</div><!-- /.page-content -->

app/views/businesses/commodity_list.js.erb
$(".main-content").html("")
$(".main-content").html("<%= escape_javascript(render partial: 'shared/list', object: @title) %>")
$(".main-content").append("<%= escape_javascript(render('shared/dialog')) %>")
			
			jQuery(function($) {
				var grid_selector = "#grid-table";
				var pager_selector = "#grid-pager";
			
				jQuery(grid_selector).jqGrid({
					url: '<%= admins_commodity_json_status_list_url %>',
					postData: {"type" : "1"},
					mType: 'get',
					datatype: 'json',
					height: '100%',
					autowidth: true,
					loadui: 'block',
					editurl: '<%= admins_commodity_update_path %>',
					caption: "审核商品",
					colNames:['id','门票名称','价格','景区','描述','门票类型','创建时间'],
					colModel:[
						{name:'id',index:'id', width:60, sorttype:"int", editable: false, sortable: true},
						{name:'name',index:'name',width:90, editable:true,editoptions:{size:"20",maxlength:"30"}, sortable: true},
						{name:'price',index:'price', width:60, sorttype:"float", editable: true, sortable: true},
						{name:'scenic',index:'scenic',width:90, editable:true, sortable: true,
						edittype:"select",editoptions:{
							size:"20",maxlength:"30",
							dataUrl:"<%= admins_scenics_type_path %>",
							buildSelect: function (data) {
								data=JSON.parse(data);
						             var s = "<select>", i, l, item;
						             if (data != null && data.length) {
						                 for (i = 0, l = data.length; i < l; i++) {
						                     item = data[i];
						                     s += '<option value="' + item.key + '">' +
						                             item.value + '</option>';
						                 }
						             }
						             return s + "</select>";
						        }
					        },
					        ajaxSelectOptions: { dataType: "json" }
							},
						{name:'description',index:'description',width:90, editable:true,editoptions:{size:"20",maxlength:"30"}, sortable: true},
						{name:'ticket_type',index:'ticket_type', width:60, sorttype:"int", editable: false, sortable: true, 
							formatter:function(value){
								if (value=1) { return '漂流'; }
								if (value=2) { return '滑雪'; }
								if (value=3) { return '游乐场'; }
								if (value=4) { return '温泉'; }
								if (value=5) { return '名山胜水'; }
								if (value=6) { return '古镇'; };
							}},
						{name:'created_at',index:'created_at', width:150,editable: false, sorttype:"date",unformat: pickDate, sortable: true}
					], 
			
					viewrecords : true,
					rowNum:10,
					rowList:[10,20,30],
					pager : pager_selector,
					altRows: true,
					//toppager: true,
					
					multiselect: false,
					//multikey: "ctrlKey",
			        multiboxonly: true,
					loadError : function(xhr, status, error){
						console.log(status + " loading data of " + $(this).attr("id") + " : " + error)
					},
					loadComplete : function() {
						var table = this;
						setTimeout(function(){
							styleCheckbox(table);
							
							updateActionIcons(table);
							updatePagerIcons(table);
							enableTooltips(table);
						}, 0);
					}
				});
			
				//enable search/filter toolbar
				//jQuery(grid_selector).jqGrid('filterToolbar',{defaultSearch:true,stringResult:true})
			
				//switch element when editing inline
				function aceSwitch( cellvalue, options, cell ) {
					setTimeout(function(){
						$(cell) .find('input[type=checkbox]')
								.wrap('<label class="inline" />')
							.addClass('ace ace-switch ace-switch-5')
							.after('<span class="lbl"></span>');
					}, 0);
				}
				//enable datepicker
				function pickDate( cellvalue, options, cell ) {
					setTimeout(function(){
						$(cell) .find('input[type=text]')
								.datepicker({format:'yyyy-mm-dd' , autoclose:true}); 
					}, 0);
				}
			
			
				//navButtons
				jQuery(grid_selector).jqGrid('navGrid',pager_selector,
					{ 	//navbar options
						edit: false,
						editicon : 'icon-pencil blue',
						add: false,
						addicon : 'icon-plus-sign purple',
						del: true,
						delicon : 'icon-trash red',
						search: false,
						searchicon : 'icon-search orange',
						refresh: true,
						refreshicon : 'icon-refresh green',
						view: true,
						viewicon : 'icon-zoom-in grey',
					},
					{
						//edit record form
						closeAfterEdit: true,
						recreateForm: true,
						beforeShowForm : function(e) {
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
							style_edit_form(form);
						}
					},
					{
						//new record form
						closeAfterAdd: true,
						recreateForm: true,
						viewPagerButtons: false,
						beforeShowForm : function(e) {
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
							style_edit_form(form);
						}
					},
					{
						//delete record form
						recreateForm: true,
						beforeShowForm : function(e) {
							var form = $(e[0]);
							if(form.data('styled')) return false;
							
							form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
							style_delete_form(form);
							
							form.data('styled', true);
						},
						onClick : function(e) {
							alert(1);
						}
					},
					{
						//search form
						recreateForm: true,
						afterShowSearch: function(e){
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-title').wrap('<div class="widget-header" />')
							style_search_form(form);
						},
						afterRedraw: function(){
							style_search_filters($(this));
						}
						,
						multipleSearch: true,
						/**
						multipleGroup:true,
						showQuery: true
						*/
					},
					{
						//view record form
						recreateForm: true,
						beforeShowForm: function(e){
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-title').wrap('<div class="widget-header" />')
						}
					}
				)
			
			
				
				function style_edit_form(form) {
					//enable datepicker on "sdate" field and switches for "stock" field
					form.find('input[name=sdate]').datepicker({format:'yyyy-mm-dd' , autoclose:true})
						.end().find('input[name=stock]')
							  .addClass('ace ace-switch ace-switch-5').wrap('<label class="inline" />').after('<span class="lbl"></span>');
			
					//update buttons classes
					var buttons = form.next().find('.EditButton .fm-button');
					buttons.addClass('btn btn-sm').find('[class*="-icon"]').remove();//ui-icon, s-icon
					buttons.eq(0).addClass('btn-primary').prepend('<i class="icon-ok"></i>');
					buttons.eq(1).prepend('<i class="icon-remove"></i>')
					
					buttons = form.next().find('.navButton a');
					buttons.find('.ui-icon').remove();
					buttons.eq(0).append('<i class="icon-chevron-left"></i>');
					buttons.eq(1).append('<i class="icon-chevron-right"></i>');		
				}
			
				function style_delete_form(form) {
					var buttons = form.next().find('.EditButton .fm-button');
					buttons.addClass('btn btn-sm').find('[class*="-icon"]').remove();//ui-icon, s-icon
					buttons.eq(0).addClass('btn-danger').prepend('<i class="icon-trash"></i>');
					buttons.eq(1).prepend('<i class="icon-remove"></i>');
					$('.ui-jqdialog-title').eq(0).html("审核商品");
					$('.delmsg').html("你确定要通过审核吗？");
					console.log($('#dData'));
					$('#dData').html("<i class=\"icon-trash\"></i>Yes");
					$('#eData').html("<i class=\"icon-remove\"></i>No");
				}
				
				function style_search_filters(form) {
					form.find('.delete-rule').val('X');
					form.find('.add-rule').addClass('btn btn-xs btn-primary');
					form.find('.add-group').addClass('btn btn-xs btn-success');
					form.find('.delete-group').addClass('btn btn-xs btn-danger');
				}
				function style_search_form(form) {
					var dialog = form.closest('.ui-jqdialog');
					var buttons = dialog.find('.EditTable')
					buttons.find('.EditButton a[id*="_reset"]').addClass('btn btn-sm btn-info').find('.ui-icon').attr('class', 'icon-retweet');
					buttons.find('.EditButton a[id*="_query"]').addClass('btn btn-sm btn-inverse').find('.ui-icon').attr('class', 'icon-comment-alt');
					buttons.find('.EditButton a[id*="_search"]').addClass('btn btn-sm btn-purple').find('.ui-icon').attr('class', 'icon-search');
				}
				
				function beforeDeleteCallback(e) {
					var form = $(e[0]);
					if(form.data('styled')) return false;
					
					form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
					style_delete_form(form);
					
					form.data('styled', true);
				}
				
				function beforeEditCallback(e) {
					var form = $(e[0]);
					form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
					style_edit_form(form);
				}
			
			
			
				//it causes some flicker when reloading or navigating grid
				//it may be possible to have some custom formatter to do this as the grid is being created to prevent this
				//or go back to default browser checkbox styles for the grid
				function styleCheckbox(table) {
				/**
					$(table).find('input:checkbox').addClass('ace')
					.wrap('<label />')
					.after('<span class="lbl align-top" />')
			
			
					$('.ui-jqgrid-labels th[id*="_cb"]:first-child')
					.find('input.cbox[type=checkbox]').addClass('ace')
					.wrap('<label />').after('<span class="lbl align-top" />');
				*/
				}
				
			
				//unlike navButtons icons, action icons in rows seem to be hard-coded
				//you can change them like this in here if you want
				function updateActionIcons(table) {
					/**
					var replacement = 
					{
						'ui-icon-pencil' : 'icon-pencil blue',
						'ui-icon-trash' : 'icon-trash red',
						'ui-icon-disk' : 'icon-ok green',
						'ui-icon-cancel' : 'icon-remove red'
					};
					$(table).find('.ui-pg-div span.ui-icon').each(function(){
						var icon = $(this);
						var $class = $.trim(icon.attr('class').replace('ui-icon', ''));
						if($class in replacement) icon.attr('class', 'ui-icon '+replacement[$class]);
					})
					*/
				}
				
				//replace icons with FontAwesome icons like above
				function updatePagerIcons(table) {
					var replacement = 
					{
						'ui-icon-seek-first' : 'icon-double-angle-left bigger-140',
						'ui-icon-seek-prev' : 'icon-angle-left bigger-140',
						'ui-icon-seek-next' : 'icon-angle-right bigger-140',
						'ui-icon-seek-end' : 'icon-double-angle-right bigger-140'
					};
					$('.ui-pg-table:not(.navtable) > tbody > tr > .ui-pg-button > .ui-icon').each(function(){
						var icon = $(this);
						var $class = $.trim(icon.attr('class').replace('ui-icon', ''));
						
						if($class in replacement) icon.attr('class', 'ui-icon '+replacement[$class]);
					})
				}
			
				function enableTooltips(table) {
					$('.navtable .ui-pg-button').tooltip({container:'body'});
					$(table).find('.ui-pg-div').tooltip({container:'body'});
				}
			
				//var selr = jQuery(grid_selector).jqGrid('getGridParam','selrow');
			
			
			});

app/views/businesses/list.js.erb
$(".main-content").html("")
$(".main-content").html("<%= escape_javascript(render partial: 'shared/list', object: @title) %>")
$(".main-content").append("<%= escape_javascript(render('shared/dialog')) %>")
			
			jQuery(function($) {
				var grid_selector = "#grid-table";
				var pager_selector = "#grid-pager";
			
				jQuery(grid_selector).jqGrid({
					url: '<%= admins_businesses_json_list_url %>',
					mType: 'get',
					datatype: 'json',
					height: '100%',
					autowidth: true,
					loadui: 'block',
					editurl: '<%= admins_businesses_update_path %>',
					caption: "管理商家",
					colNames:['id','商家名称','营业执照','法人名称','法人照片','创建时间'],
					colModel:[
						{name:'id',index:'id', width:60, sorttype:"int", editable: false, sortable: true},
						{name:'name',index:'name',width:90, editable:true, sortable: true},
						{name:'operating_license',index:'operating_license', width:60, editable: true, sortable: true,
						  hidden: true, edittype: "image",
							editoptions: {size:"20",maxlength:"30",src: ""},
							editrules: {edithidden: true}},
						{name:'legal_person_name',index:'legal_person_name',width:90, editable:true, sortable: true},
						{name:'legal_person_photo',index:'legal_person_photo',width:90, editable:true, sortable: true,
							hidden: true, edittype: "image", 
							editoptions:{size:"20",maxlength:"30", src: ""}, 
              editrules: {edithidden: true}},
						{name:'created_at',index:'created_at', width:150,editable: false, sorttype:"date", format: pickDate, sortable: true}
					], 
			
					viewrecords : true,
					rowNum:10,
					rowList:[10,20,30],
					pager : pager_selector,
					altRows: true,
					//toppager: true,
					
					multiselect: false,
					//multikey: "ctrlKey",
			        multiboxonly: true,
					loadError : function(xhr, status, error){
						console.log(status + " loading data of " + $(this).attr("id") + " : " + error)
					},
					loadComplete : function() {
						var table = this;
						setTimeout(function(){
							styleCheckbox(table);
							
							updateActionIcons(table);
							updatePagerIcons(table);
							enableTooltips(table);
						}, 0);
					}
				});
			
				//enable search/filter toolbar
				//jQuery(grid_selector).jqGrid('filterToolbar',{defaultSearch:true,stringResult:true})
			
				//switch element when editing inline
				function aceSwitch( cellvalue, options, cell ) {
					setTimeout(function(){
						$(cell) .find('input[type=checkbox]')
								.wrap('<label class="inline" />')
							.addClass('ace ace-switch ace-switch-5')
							.after('<span class="lbl"></span>');
					}, 0);
				}
				//enable datepicker
				function pickDate( cellvalue, options, cell ) {
					setTimeout(function(){
						$(cell) .find('input[type=text]')
								.datepicker({format:'yyyy-mm-dd' , autoclose:true}); 
					}, 0);
				}
			
			
				//navButtons
				jQuery(grid_selector).jqGrid('navGrid',pager_selector,
					{ 	//navbar options
						edit: true,
						editicon : 'icon-pencil blue',
						add: false,
						addicon : 'icon-plus-sign purple',
						del: true,
						delicon : 'icon-trash red',
						search: false,
						searchicon : 'icon-search orange',
						refresh: true,
						refreshicon : 'icon-refresh green',
						view: true,
						viewicon : 'icon-zoom-in grey',
					},
					{
						//edit record form
						closeAfterEdit: true,
						recreateForm: true,
						beforeShowForm : function(e) {
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
							style_edit_form(form);
						},
						beforeInitData: function (e) {
              var $self = $(this);

              //operating_license
              cm = $self.jqGrid("getColProp", "operating_license");
              selRowId = $self.jqGrid("getGridParam", "selrow");
              cellvalue=$self.jqGrid("getCell", selRowId, 2);
              cm.editoptions.src = cellvalue;

              //legal_person_photo
              cm = $self.jqGrid("getColProp", "legal_person_photo");
              selRowId = $self.jqGrid("getGridParam", "selrow");
              cellvalue=$self.jqGrid("getCell", selRowId, 4);
              cm.editoptions.src = cellvalue;
            },
            afterclickPgButtons: function (e) {
             	console.log(e);
              var $self = $(this),
                  selRowId = $self.jqGrid("getGridParam", "selrow");
              $("#flag").attr("src", "http://www.ok-soft-gmbh.com/img/flag_" + selRowId + ".gif");
            }
					},
					{
						//new record form
						closeAfterAdd: true,
						recreateForm: true,
						viewPagerButtons: false,
						beforeShowForm : function(e) {
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
							style_edit_form(form);
						}
					},
					{
						//delete record form
						recreateForm: true,
						beforeShowForm : function(e) {
							var form = $(e[0]);
							if(form.data('styled')) return false;
							
							form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
							style_delete_form(form);
							
							form.data('styled', true);
						},
						onClick : function(e) {
							alert(1);
						}
					},
					{
						//search form
						recreateForm: true,
						afterShowSearch: function(e){
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-title').wrap('<div class="widget-header" />')
							style_search_form(form);
						},
						afterRedraw: function(){
							style_search_filters($(this));
						}
						,
						multipleSearch: true,
						/**
						multipleGroup:true,
						showQuery: true
						*/
					},
					{
						//view record form
						recreateForm: true,
						beforeShowForm: function(e){
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-title').wrap('<div class="widget-header" />')
						}
					}
				)
			
			
				
				function style_edit_form(form) {
					//enable datepicker on "sdate" field and switches for "stock" field
					form.find('input[name=sdate]').datepicker({format:'yyyy-mm-dd' , autoclose:true})
						.end().find('input[name=stock]')
							  .addClass('ace ace-switch ace-switch-5').wrap('<label class="inline" />').after('<span class="lbl"></span>');
			
					//update buttons classes
					var buttons = form.next().find('.EditButton .fm-button');
					buttons.addClass('btn btn-sm').find('[class*="-icon"]').remove();//ui-icon, s-icon
					buttons.eq(0).addClass('btn-primary').prepend('<i class="icon-ok"></i>');
					buttons.eq(1).prepend('<i class="icon-remove"></i>')
					
					buttons = form.next().find('.navButton a');
					buttons.find('.ui-icon').remove();
					buttons.eq(0).append('<i class="icon-chevron-left"></i>');
					buttons.eq(1).append('<i class="icon-chevron-right"></i>');		
				}
			
				function style_delete_form(form) {
					var buttons = form.next().find('.EditButton .fm-button');
					buttons.addClass('btn btn-sm').find('[class*="-icon"]').remove();//ui-icon, s-icon
					buttons.eq(0).addClass('btn-danger').prepend('<i class="icon-trash"></i>');
					buttons.eq(1).prepend('<i class="icon-remove"></i>');
				}
				
				function style_search_filters(form) {
					form.find('.delete-rule').val('X');
					form.find('.add-rule').addClass('btn btn-xs btn-primary');
					form.find('.add-group').addClass('btn btn-xs btn-success');
					form.find('.delete-group').addClass('btn btn-xs btn-danger');
				}
				function style_search_form(form) {
					var dialog = form.closest('.ui-jqdialog');
					var buttons = dialog.find('.EditTable')
					buttons.find('.EditButton a[id*="_reset"]').addClass('btn btn-sm btn-info').find('.ui-icon').attr('class', 'icon-retweet');
					buttons.find('.EditButton a[id*="_query"]').addClass('btn btn-sm btn-inverse').find('.ui-icon').attr('class', 'icon-comment-alt');
					buttons.find('.EditButton a[id*="_search"]').addClass('btn btn-sm btn-purple').find('.ui-icon').attr('class', 'icon-search');
				}
				
				function beforeDeleteCallback(e) {
					var form = $(e[0]);
					if(form.data('styled')) return false;
					
					form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
					style_delete_form(form);
					
					form.data('styled', true);
				}
				
				function beforeEditCallback(e) {
					var form = $(e[0]);
					form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
					style_edit_form(form);
				}
			
			
			
				//it causes some flicker when reloading or navigating grid
				//it may be possible to have some custom formatter to do this as the grid is being created to prevent this
				//or go back to default browser checkbox styles for the grid
				function styleCheckbox(table) {
				/**
					$(table).find('input:checkbox').addClass('ace')
					.wrap('<label />')
					.after('<span class="lbl align-top" />')
			
			
					$('.ui-jqgrid-labels th[id*="_cb"]:first-child')
					.find('input.cbox[type=checkbox]').addClass('ace')
					.wrap('<label />').after('<span class="lbl align-top" />');
				*/
				}
				
			
				//unlike navButtons icons, action icons in rows seem to be hard-coded
				//you can change them like this in here if you want
				function updateActionIcons(table) {
					/**
					var replacement = 
					{
						'ui-icon-pencil' : 'icon-pencil blue',
						'ui-icon-trash' : 'icon-trash red',
						'ui-icon-disk' : 'icon-ok green',
						'ui-icon-cancel' : 'icon-remove red'
					};
					$(table).find('.ui-pg-div span.ui-icon').each(function(){
						var icon = $(this);
						var $class = $.trim(icon.attr('class').replace('ui-icon', ''));
						if($class in replacement) icon.attr('class', 'ui-icon '+replacement[$class]);
					})
					*/
				}
				
				//replace icons with FontAwesome icons like above
				function updatePagerIcons(table) {
					var replacement = 
					{
						'ui-icon-seek-first' : 'icon-double-angle-left bigger-140',
						'ui-icon-seek-prev' : 'icon-angle-left bigger-140',
						'ui-icon-seek-next' : 'icon-angle-right bigger-140',
						'ui-icon-seek-end' : 'icon-double-angle-right bigger-140'
					};
					$('.ui-pg-table:not(.navtable) > tbody > tr > .ui-pg-button > .ui-icon').each(function(){
						var icon = $(this);
						var $class = $.trim(icon.attr('class').replace('ui-icon', ''));
						
						if($class in replacement) icon.attr('class', 'ui-icon '+replacement[$class]);
					})
				}
			
				function enableTooltips(table) {
					$('.navtable .ui-pg-button').tooltip({container:'body'});
					$(table).find('.ui-pg-div').tooltip({container:'body'});
				}
			
				//var selr = jQuery(grid_selector).jqGrid('getGridParam','selrow');
			
			
			});

app/views/businesses/statistics.js.erb
$(".main-content").html("<%= escape_javascript(render('businesses/business_statistics')) %>")
$(function(){

  chart1 = new Highcharts.Chart({
        chart: {
          renderTo: 'container1',
          type: 'column'
        },
        title: {
            text: '统计商家'
        },
        credits: {
          enabled: false
        },
        xAxis: {
            categories: [ <%= @categories %> ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: '商家个数'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y} 个</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: '商家个数',
            data: <%= @businesses %>
          }
        ]
    });
});
  