config/routes.rb
Rails.application.routes.draw do
  get 'admins/login' => 'admins#login'
  get 'admins/logout' => 'sessions#destroy'
  get 'admins/list' => 'admins#list'
  post 'admins/update' => 'admins#admin_update'
  get 'admins/workload' => 'admins#admin_statistics_workload'
  get 'admins/jsonworkload' => 'admins#admin_workload_json'
  get 'admins/jsonlist' => 'admins#jsonlist'
  get 'admins/commodity/status_list' => 'commodity#status_list'
  get 'admins/commodity/json_status_list' => 'commodity#json_status_list'
  post 'admins/commodity/pass' => 'commodity#pass'
  post 'admins/commodity/update' => 'commodity#admin_update'
  get 'admins/businesses/status_list' => 'businesses#status_list'
  get 'admins/businesses/json_status_list' => 'businesses#json_status_list'
  post 'admins/businesses/pass' => 'businesses#pass'
  post 'admins/businesses/update' => 'businesses#admin_update'
  get 'admins/businesses/list' => 'businesses#list'
  get 'admins/businesses/json_list' => 'businesses#json_list'
  get 'admins/businesses/statistics' => 'businesses#statistics'
  get 'admins/businesses/json_statistics' => 'businesses#json_statistics'
  get 'admins/scenics/type' =>'scenics#scenics_option'
  get '/admins/commodity/list' => 'commodity#commodity_list'
  get '/admins/commodity/json_list' => 'commodity#commodity_json_list'
  get '/admins/orders/statistics' => 'orders#statistics'
  namespace :admins do

  end
  resources :admins
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/views/admins/_admin_info.html.erb
<div class="breadcrumbs" id="breadcrumbs">
	<script type="text/javascript">
		try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
	</script>

	<ul class="breadcrumb">
		<li>
			<i class="icon-home home-icon"></i>
				<a href="#">首页</a>
			</li>
		<li class="active">个人资料</li>
	</ul><!-- /.breadcrumb -->
</div>

<div class="page-content">
	<!-- <div class="center">
		<div class="row">
			<div class="col-xs-3">
				个人资料
			</div>
		</div>
		<div class="divider"></div>
		<%= form_for @admin, url: admin_path(@admin), method: :patch, remote: true do |f| %>
		<div class="row">
			<div class="col-xs-3">
				<%= f.label :name %>
			</div>
			<div class="col-xs-9">
				<%= f.text_field :name %>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<%= f.submit "保存", :disable_with => '保存ing...' %>
			</div>
		</div>
		<% end %>
		<div class="row">
			<div class="col-xs-3">
				修改密码
			</div>
		</div>
		<div class="divider"></div>
	</div> -->
	<%= render 'admin_profile' %>
</div><!-- /.page-content -->

app/views/admins/_admin_profile.html.erb
<div>
	<div class="col-xs-3">个人资料</div>
</div>
<hr>
<%= form_for @admin, url: admin_path(@admin), method: :patch, remote: true do |f| %>
<div class="profile-user-info profile-user-info-striped">
	<div class="profile-info-row">
		<div class="profile-info-name"> 昵称 </div>
		<div class="profile-info-value">
			<%= f.text_field :name %>
		</div>
	</div>
	<div class="profile-info-row center">
		<div class="profile-info-name"> 操作 </div>
		<div class="profile-info-value">
				<%= f.submit "保存", :disable_with => '保存ing...', class: "btn btn-primary" %>
		</div>
	</div>
</div>
<% end %>
<div class="row"><div>&nbsp;</div></div>
<div>
	<div class="col-xs-3">修改密码</div>
</div>
<hr>
<%= form_for @admin, url: admin_path(@admin), method: :patch, remote: true do |f| %>
<div class="profile-user-info profile-user-info-striped">
	<div class="profile-info-row">
		<div class="profile-info-name"> 旧密码 </div>
		<div class="profile-info-value">
			<%= f.password_field :password_old %>
		</div>
	</div>
	<div class="profile-info-row">
		<div class="profile-info-name"> 新密码 </div>
		<div class="profile-info-value">
			<%= f.password_field :password_new %>
		</div>
	</div>
	<div class="profile-info-row">
		<div class="profile-info-name"> 新密码确认 </div>
		<div class="profile-info-value">
			<%= f.password_field :password_new_confirmation %>
		</div>
	</div>
	<div class="profile-info-row center">
		<div class="profile-info-name"> 操作 </div>
		<div class="profile-info-value">
				<%= f.submit "保存", :disable_with => '保存ing...', class: "btn btn-primary" %>
		</div>
	</div>
</div>
<% end %>
<%= render 'shared/dialog' %>

app/views/admins/_admin_statistics_workload.html.erb
<div class="breadcrumbs" id="breadcrumbs">

	<ul class="breadcrumb">
		<li>
			<i class="icon-home home-icon"></i>
				<a href="#">首页</a>
			</li>
		<li class="active">统计平台管理员工作量</li>
	</ul><!-- /.breadcrumb -->
</div>

<div class="page-content">
	<script src="assets/highcharts.js"></script>
	<!-- <script src="assets/exporting.js"></script> -->
	<!-- <div style="min-width: 310px; height: 400px; margin: 0 auto"> -->
		<span id="container1" style="float:left;min-width: 450px; height: 400px; margin: 0 auto"></span>
		<span id="container2" style="min-width: 450px; height: 400px; margin: 0 auto"></span>
	<!-- </div> -->
</div><!-- /.page-content -->

app/views/admins/_index_content.html.erb
<div class="breadcrumbs" id="breadcrumbs">

	<ul class="breadcrumb">
		<li>
			<i class="icon-home home-icon"></i>
				<a href="#">首页</a>
			</li>
		<li class="active">控制台</li>
	</ul><!-- /.breadcrumb -->
</div>

<div class="page-content">
	
</div><!-- /.page-content -->

app/views/admins/admin_statistics_workload.js.erb
$(".main-content").html("")
$(".main-content").html("<%= escape_javascript(render('admins/admin_statistics_workload')) %>")
$(function () {
    charts1=new Highcharts.Chart({
        chart: {
            renderTo: 'container1',
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: '审核商家工作量统计'
        },
        credits: {
        	enabled: false
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
            	   events:{
            	   	click: function(e){
            	   		console.log(e.point.id)
            	   	}
            	   },
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            type: 'pie',
            name: '审核商家工作量统计'
        }]
    });
		//异步请求数据
                $.ajax({
                    type:"GET",
                    url:'<%= admins_jsonworkload_path+"?type=0" %>',
                    success:function(data){
                        //设置数据
                        charts1.series[0].setData(data);  
                    },
                    error:function(e){
                        console.log(e);
                    }
                });

    charts2=new Highcharts.Chart({
        chart: {
        	renderTo: 'container2',
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: '审核商品工作量统计'
        },
        credits: {
        	enabled: false
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
            	   events:{
            	   	click: function(e){
            	   		console.log(e.point.name)
            	   	}
            	   },
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            type: 'pie',
            name: '审核商品工作量统计'
        }]
    });

		//异步请求数据
                $.ajax({
                    type:"GET",
                    url:'<%= admins_jsonworkload_path+"?type=1" %>',
                    success:function(data){
                        //设置数据
                        charts2.series[0].setData(data);  
                    },
                    error:function(e){
                        console.log(e);
                    }
                });
});

app/views/admins/admin_update.js.erb
<% if @result %>
	$(".modal-body>p").html("")
	$(".modal-body>p").html("操作成功")
<% else %>
	$(".modal-body>p").html("")
	$(".modal-body>p").html("操作失败")
<% end %>
$('h4.modal-title').html("")
$('h4.modal-title').html("操作结果")
$('#myModal').modal('toggle')
$('#myModal').modal('show')

app/views/admins/index.html.erb
		<div class="navbar navbar-default" id="navbar">
			<script type="text/javascript">
				try{ace.settings.check('navbar' , 'fixed')}catch(e){}
			</script>

			<div class="navbar-container" id="navbar-container">
				<div class="navbar-header pull-left">
					<a href="#" class="navbar-brand">
						<small>
							<i class="icon-leaf"></i>
							e-yoo.com后台管理系统
						</small>
					</a><!-- /.brand -->
				</div><!-- /.navbar-header -->

				<div class="navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">
						<li class="light-blue">
							<a data-toggle="dropdown" href="#" class="dropdown-toggle">
								<img class="nav-user-photo" src="/assets/avatar2.png" alt="Jason's Photo" />
								<span class="user-info">
									<small>欢迎光临,</small>
									<%= current_admin.name %>
								</span>

								<i class="icon-caret-down"></i>
							</a>

							<ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
								<!-- <li>
									<a href="#">
										<i class="icon-cog"></i>
										设置
									</a>
								</li> -->

								<li>
									<%= link_to admin_path(current_admin), remote:true do %>
										<i class="icon-user"></i>
										个人资料
									<% end %>
								</li>

								<li class="divider"></li>

								<li>
									<%= link_to admins_logout_path do %>
									<i class="icon-off"></i>
										退出
									<!-- <a href="">
										<i class="icon-off"></i>
										退出
									</a> -->
									<% end %>
								</li>
							</ul>
						</li>
					</ul><!-- /.ace-nav -->
				</div><!-- /.navbar-header -->
			</div><!-- /.container -->
		</div>

		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<div class="main-container-inner">
				<a class="menu-toggler" id="menu-toggler" href="#">
					<span class="menu-text"></span>
				</a>

				<div class="sidebar" id="sidebar">
					<script type="text/javascript">
						function change_active(element){
							var menu_item=$(".nav.nav-list>li")
							$.each(menu_item, function(index, val) {
								 $(val).removeClass('active')
							});
							$(element).addClass('active')
						}
					</script>

					<ul class="nav nav-list">
						<li class="active">
							<%= link_to admins_path do %>
								<i class="icon-dashboard"></i>
								<span class="menu-text"> 控制台 </span>
							<% end %>
						</li>

						<!-- <li>
							<a href="#" class="dropdown-toggle">
								<i class="icon-desktop"></i>
								<span class="menu-text"> UI 组件 </span>
								<b class="arrow icon-angle-down"></b>
							</a>
						</li> -->

						<% if !@menu.nil? && @menu.length>0 %>
							<% @menu.each do |m| %>
							<li onClick="change_active(this)">
								<%= link_to m[:link], class: (!m[:items].nil?&&m[:items].length>0? "dropdown-toggle" : "") , remote: true do %>
									<i class="icon-desktop"></i>
									<span class="menu-text"> <%= m[:name] %> </span>
									<% if !m[:items].nil?&&m[:items].length>0 %>
										<b class="arrow icon-angle-down"></b>
									<% end %>
								<% end %>
							</li>
							<% end %>
						<% end %>
						
					</ul><!-- /.nav-list -->

					<div class="sidebar-collapse" id="sidebar-collapse">
						<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
					</div>

					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
					</script>
				</div>

				<div class="main-content">
					<%= render 'index_content' %>
				</div><!-- /.main-content -->

			</div><!-- /.main-container-inner -->

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="icon-double-angle-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<script src="/assets/jquery-ui-1.10.3.custom.min.js"></script>

		<!-- ace scripts -->

		<script src="/assets/ace-elements.min.js"></script>

app/views/admins/list.js.erb
$(".main-content").html("")
$(".main-content").html("<%= escape_javascript(render partial: 'shared/list', object: @title) %>")
$(".main-content").append("<%= escape_javascript(render('shared/dialog')) %>")
			
			jQuery(function($) {
				var grid_selector = "#grid-table";
				var pager_selector = "#grid-pager";
			
				jQuery(grid_selector).jqGrid({
					url: '<%= admins_jsonlist_url %>',
					postData: {"type" : "1"},
					mType: 'get',
					datatype: 'json',
					height: '100%',
					autowidth: true,
					loadui: 'block',
					editurl: '<%= admins_update_path %>',
					caption: "管理平台管理员",
					colNames:['id','管理员账号','管理员名字','创建时间'],
					colModel:[
						{name:'id',index:'id', width:60, sorttype:"int", editable: false, sortable: true},
						{name:'account',index:'account', width:60, sorttype:"int", editable: true, sortable: true},
						{name:'name',index:'name',width:90, editable:true,editoptions:{size:"20",maxlength:"30"}, sortable: true},
						{name:'created_at',index:'created_at', width:150,editable: false, sorttype:"date",unformat: pickDate, sortable: true}
					], 
			
					viewrecords : true,
					rowNum:10,
					rowList:[10,20,30],
					pager : pager_selector,
					altRows: true,
					//toppager: true,
					
					multiselect: false,
					//multikey: "ctrlKey",
			        multiboxonly: true,
					loadError : function(xhr, status, error){
						console.log(status + " loading data of " + $(this).attr("id") + " : " + error)
					},
					loadComplete : function() {
						var table = this;
						setTimeout(function(){
							styleCheckbox(table);
							
							updateActionIcons(table);
							updatePagerIcons(table);
							enableTooltips(table);
						}, 0);
					}
				});
			
				//enable search/filter toolbar
				//jQuery(grid_selector).jqGrid('filterToolbar',{defaultSearch:true,stringResult:true})
			
				//switch element when editing inline
				function aceSwitch( cellvalue, options, cell ) {
					setTimeout(function(){
						$(cell) .find('input[type=checkbox]')
								.wrap('<label class="inline" />')
							.addClass('ace ace-switch ace-switch-5')
							.after('<span class="lbl"></span>');
					}, 0);
				}
				//enable datepicker
				function pickDate( cellvalue, options, cell ) {
					setTimeout(function(){
						$(cell) .find('input[type=text]')
								.datepicker({format:'yyyy-mm-dd' , autoclose:true}); 
					}, 0);
				}
			
			
				//navButtons
				jQuery(grid_selector).jqGrid('navGrid',pager_selector,
					{ 	//navbar options
						edit: true,
						editicon : 'icon-pencil blue',
						add: true,
						addicon : 'icon-plus-sign purple',
						del: true,
						delicon : 'icon-trash red',
						search: false,
						searchicon : 'icon-search orange',
						refresh: true,
						refreshicon : 'icon-refresh green',
						view: true,
						viewicon : 'icon-zoom-in grey',
					},
					{
						//edit record form
						closeAfterEdit: true,
						recreateForm: true,
						beforeShowForm : function(e) {
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
							style_edit_form(form);
						}
					},
					{
						//new record form
						closeAfterAdd: true,
						recreateForm: true,
						viewPagerButtons: false,
						beforeShowForm : function(e) {
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
							style_edit_form(form);
						}
					},
					{
						//delete record form
						recreateForm: true,
						beforeShowForm : function(e) {
							var form = $(e[0]);
							if(form.data('styled')) return false;
							
							form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
							style_delete_form(form);
							
							form.data('styled', true);
						},
						onClick : function(e) {
							alert(1);
						}
					},
					{
						//search form
						recreateForm: true,
						afterShowSearch: function(e){
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-title').wrap('<div class="widget-header" />')
							style_search_form(form);
						},
						afterRedraw: function(){
							style_search_filters($(this));
						}
						,
						multipleSearch: true,
						/**
						multipleGroup:true,
						showQuery: true
						*/
					},
					{
						//view record form
						recreateForm: true,
						beforeShowForm: function(e){
							var form = $(e[0]);
							form.closest('.ui-jqdialog').find('.ui-jqdialog-title').wrap('<div class="widget-header" />')
						}
					}
				)
			
			
				
				function style_edit_form(form) {
					//enable datepicker on "sdate" field and switches for "stock" field
					form.find('input[name=sdate]').datepicker({format:'yyyy-mm-dd' , autoclose:true})
						.end().find('input[name=stock]')
							  .addClass('ace ace-switch ace-switch-5').wrap('<label class="inline" />').after('<span class="lbl"></span>');
			
					//update buttons classes
					var buttons = form.next().find('.EditButton .fm-button');
					buttons.addClass('btn btn-sm').find('[class*="-icon"]').remove();//ui-icon, s-icon
					buttons.eq(0).addClass('btn-primary').prepend('<i class="icon-ok"></i>');
					buttons.eq(1).prepend('<i class="icon-remove"></i>')
					
					buttons = form.next().find('.navButton a');
					buttons.find('.ui-icon').remove();
					buttons.eq(0).append('<i class="icon-chevron-left"></i>');
					buttons.eq(1).append('<i class="icon-chevron-right"></i>');		
				}
			
				function style_delete_form(form) {
					var buttons = form.next().find('.EditButton .fm-button');
					buttons.addClass('btn btn-sm').find('[class*="-icon"]').remove();//ui-icon, s-icon
					buttons.eq(0).addClass('btn-danger').prepend('<i class="icon-trash"></i>');
					buttons.eq(1).prepend('<i class="icon-remove"></i>')
				}
				
				function style_search_filters(form) {
					form.find('.delete-rule').val('X');
					form.find('.add-rule').addClass('btn btn-xs btn-primary');
					form.find('.add-group').addClass('btn btn-xs btn-success');
					form.find('.delete-group').addClass('btn btn-xs btn-danger');
				}
				function style_search_form(form) {
					var dialog = form.closest('.ui-jqdialog');
					var buttons = dialog.find('.EditTable')
					buttons.find('.EditButton a[id*="_reset"]').addClass('btn btn-sm btn-info').find('.ui-icon').attr('class', 'icon-retweet');
					buttons.find('.EditButton a[id*="_query"]').addClass('btn btn-sm btn-inverse').find('.ui-icon').attr('class', 'icon-comment-alt');
					buttons.find('.EditButton a[id*="_search"]').addClass('btn btn-sm btn-purple').find('.ui-icon').attr('class', 'icon-search');
				}
				
				function beforeDeleteCallback(e) {
					var form = $(e[0]);
					if(form.data('styled')) return false;
					
					form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
					style_delete_form(form);
					
					form.data('styled', true);
				}
				
				function beforeEditCallback(e) {
					var form = $(e[0]);
					form.closest('.ui-jqdialog').find('.ui-jqdialog-titlebar').wrapInner('<div class="widget-header" />')
					style_edit_form(form);
				}
			
			
			
				//it causes some flicker when reloading or navigating grid
				//it may be possible to have some custom formatter to do this as the grid is being created to prevent this
				//or go back to default browser checkbox styles for the grid
				function styleCheckbox(table) {
				/**
					$(table).find('input:checkbox').addClass('ace')
					.wrap('<label />')
					.after('<span class="lbl align-top" />')
			
			
					$('.ui-jqgrid-labels th[id*="_cb"]:first-child')
					.find('input.cbox[type=checkbox]').addClass('ace')
					.wrap('<label />').after('<span class="lbl align-top" />');
				*/
				}
				
			
				//unlike navButtons icons, action icons in rows seem to be hard-coded
				//you can change them like this in here if you want
				function updateActionIcons(table) {
					/**
					var replacement = 
					{
						'ui-icon-pencil' : 'icon-pencil blue',
						'ui-icon-trash' : 'icon-trash red',
						'ui-icon-disk' : 'icon-ok green',
						'ui-icon-cancel' : 'icon-remove red'
					};
					$(table).find('.ui-pg-div span.ui-icon').each(function(){
						var icon = $(this);
						var $class = $.trim(icon.attr('class').replace('ui-icon', ''));
						if($class in replacement) icon.attr('class', 'ui-icon '+replacement[$class]);
					})
					*/
				}
				
				//replace icons with FontAwesome icons like above
				function updatePagerIcons(table) {
					var replacement = 
					{
						'ui-icon-seek-first' : 'icon-double-angle-left bigger-140',
						'ui-icon-seek-prev' : 'icon-angle-left bigger-140',
						'ui-icon-seek-next' : 'icon-angle-right bigger-140',
						'ui-icon-seek-end' : 'icon-double-angle-right bigger-140'
					};
					$('.ui-pg-table:not(.navtable) > tbody > tr > .ui-pg-button > .ui-icon').each(function(){
						var icon = $(this);
						var $class = $.trim(icon.attr('class').replace('ui-icon', ''));
						
						if($class in replacement) icon.attr('class', 'ui-icon '+replacement[$class]);
					})
				}
			
				function enableTooltips(table) {
					$('.navtable .ui-pg-button').tooltip({container:'body'});
					$(table).find('.ui-pg-div').tooltip({container:'body'});
				}
			
				//var selr = jQuery(grid_selector).jqGrid('getGridParam','selrow');
			
			
			});

app/views/admins/login.html.erb
		<div class="main-container">
			<div class="main-content">
			<div class="row center">
				<% flash.each do |key, value| %>
				      <div class="alert alert-<%= key %>"><%= value %></div>
				<% end %>
			</div>
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
							<div class="center">
								<h1>
									<i class="icon-leaf green"></i>
									<span class="red">Ace</span>
									<span class="white">Application</span>
								</h1>
								<h4 class="blue">&copy; e-yoo.com</h4>
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="login-box" class="login-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header blue lighter bigger">
												<i class="icon-coffee green"></i>
												Please Enter Your Information
											</h4>

											<div class="space-6"></div>

											<%= form_for(:session, url: sessions_path) do |f| %>
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<!-- <input type="text" class="form-control" placeholder="Username" /> -->
															<%= f.text_field :account, class: "form-control", placeholder: "Username" %>
															<i class="icon-user"></i>
														</span> 
													</label>

													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<!-- <input type="password" class="form-control" placeholder="Password" /> -->
															<%= f.password_field :password, class: "form-control", placeholder: "Password" %>
															<i class="icon-lock"></i>
														</span>
													</label>

													<div class="space"></div>

													<div class="clearfix">
														<label class="inline">
															<input type="checkbox" class="ace" />
															<span class="lbl"> Remember Me</span>
														</label>

														<!-- <button type="button" class="width-35 pull-right btn btn-sm btn-primary">
															<i class="icon-key"></i>
															Login
														</button> -->
														<%= f.submit "Login", class: "width-35 pull-right btn btn-sm btn-primary" %>
													</div>

													<div class="space-4"></div>
												</fieldset>
											<% end %>
										</div><!-- /widget-main -->

										<div class="toolbar clearfix">
											<div>
												<a href="#" onclick="show_box('forgot-box'); return false;" class="forgot-password-link">
													<i class="icon-arrow-left"></i>
													I forgot my password
												</a>
											</div>
										</div>
									</div><!-- /widget-body -->
								</div><!-- /login-box -->

								<div id="forgot-box" class="forgot-box widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header red lighter bigger">
												<i class="icon-key"></i>
												Retrieve Password
											</h4>

											<div class="space-6"></div>
											<p>
												Enter your email and to receive instructions
											</p>

											<form>
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="email" class="form-control" placeholder="Email" />
															<i class="icon-envelope"></i>
														</span>
													</label>

													<div class="clearfix">
														<button type="button" class="width-35 pull-right btn btn-sm btn-danger">
															<i class="icon-lightbulb"></i>
															Send Me!
														</button>
													</div>
												</fieldset>
											</form>
										</div><!-- /widget-main -->

										<div class="toolbar center">
											<a href="#" onclick="show_box('login-box'); return false;" class="back-to-login-link">
												Back to login
												<i class="icon-arrow-right"></i>
											</a>
										</div>
									</div><!-- /widget-body -->
								</div><!-- /forgot-box -->

								
							</div><!-- /position-relative -->
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div>
		</div><!-- /.main-container -->

		<!-- basic scripts -->
		<!-- inline scripts related to this page -->

		<script type="text/javascript">
			$('body').addClass('login-layout');
			function show_box(id) {
			 jQuery('.widget-box.visible').removeClass('visible');
			 jQuery('#'+id).addClass('visible');
			}
		</script>

app/views/admins/show.js.erb
$(".main-content").html("")
$(".main-content").html("<%= escape_javascript(render('admins/admin_info')) %>")
var menu_item=$(".nav.nav-list>li")
$.each(menu_item, function(index, val) {
	 $(val).removeClass('active')
});

app/views/admins/update.js.erb
<% if @result %>
	$(".modal-body>p").html("")
	$(".modal-body>p").html("修改成功")
<% end %>
$('#myModal').modal('toggle')
$('#myModal').modal('show')